# Generated by Django 2.1.7 on 2019-02-14 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190214_0102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
